apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/instance: default
    app.kubernetes.io/part-of: tekton-chains
  name: chains-config
  namespace: tekton-chains
data:
  artifacts.oci.format: simplesigning
  artifacts.oci.signer: x509
  artifacts.oci.storage: oci
  artifacts.pipelinerun.format: in-toto
  artifacts.pipelinerun.signer: x509
  artifacts.pipelinerun.storage: oci
  artifacts.taskrun.format: in-toto
  artifacts.taskrun.signer: x509
  artifacts.taskrun.storage: oci
  signers.x509.fulcio.enabled: "true"
  transparency.enabled: "true"
