apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/instance: default
    app.kubernetes.io/part-of: tekton-chains
  name: chains-config
  namespace: tekton-chains
data:
  artifacts.oci.format: simplesigning
  artifacts.oci.signer: kms
  artifacts.oci.storage: "" # disabled
  artifacts.pipelinerun.format: slsa/v1
  artifacts.pipelinerun.signer: kms
  artifacts.pipelinerun.storage: grafeas
  artifacts.taskrun.format: slsa/v1
  artifacts.taskrun.signer: kms
  artifacts.pipelinerun.enable-deep-inspection: "true"
  artifacts.taskrun.storage: "" # disabled
  signers.kms.kmsref: gcpkms://projects/${PROJECT_ID}/locations/${LOCATION}/keyRings/${KEYRING}/cryptoKeys/${KEY}/cryptoKeyVersions/1
  signers.x509.fulcio.enabled: "false"
  storage.grafeas.projectid: $PROJECT_ID
  transparency.enabled: "false"
