apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/instance: default
    app.kubernetes.io/part-of: tekton-chains
  name: chains-config
  namespace: tekton-chains
data:
  artifacts.oci.format: simplesigning
  artifacts.oci.signer: kms
  artifacts.oci.storage: grafeas,oci
  artifacts.pipelinerun.format: in-toto
  artifacts.pipelinerun.signer: kms
  artifacts.pipelinerun.storage: grafeas,oci
  artifacts.taskrun.format: in-toto
  artifacts.taskrun.signer: kms
  artifacts.taskrun.storage: grafeas,oci
  signers.kms.kmsref: gcpkms://projects/galloro-demos/locations/europe-west1/keyRings/binauthz/cryptoKeys/tekton-chains/cryptoKeyVersions/1
  signers.x509.fulcio.enabled: "false"
  storage.grafeas.projectid: galloro-demos
  transparency.enabled: "false"
