apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: pipeline-clone-and-build
spec:
  params:
    - name: git-url
    - name: image-name
  workspaces:
    - name: source
  results:
    - name: git-url
      description: Source code used to build the artifact.
      value: $(tasks.git-clone.results.url)
    - name: git-commit
      description: The commit used to build the artifact.
      value: $(tasks.git-clone.results.commit)
    - name: image-url
      description: The image url.
      value: $(tasks.image-build.results.IMAGE_URL)
    - name: image-digest
      description: The image digest.
      value: $(tasks.image-build.results.IMAGE_DIGEST)
  tasks:
    - name: git-clone
      taskRef:
        name: git-clone
      params:
        - name: url
          value: $(params.git-url)
      workspaces:
        - name: source
          workspace: source
    - name: image-build
      taskRef:
        name: image-build
      runAfter:
        - git-clone
      params:
        - name: IMAGE
          value: $(params.image-name)
        - name: commit
          value: "$(tasks.git-clone.results.commit)"
      workspaces:
        - name: source
          workspace: source