apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: pipeline-clone-and-build
spec:
  params:
    - name: git-url
    - name: image-name
  workspaces:
    - name: source
  results:
    - name: IMAGE_DIGEST
      description: Digest of the image just built.
      value: $(tasks.image-build.results.IMAGE_DIGEST)
    - name: IMAGE_URL
      description: URL of the image just built.
      value: $(tasks.image-build.results.IMAGE_URL)
  tasks:
    - name: git-clone
      taskRef:
        name: git-clone
      params:
        - name: url
          value: $(params.git-url)
      workspaces:
        - name: source
          workspace: source
    - name: image-build
      taskRef:
        name: image-build
      runAfter:
        - git-clone
      params:
        - name: IMAGE
          value: $(params.image-name)
        - name: CHAINS-GIT_COMMIT
          value: "$(tasks.git-clone.results.commit)"
        - name: CHAINS-GIT_URL
          value: "$(tasks.git-clone.results.url)"
      workspaces:
        - name: source
          workspace: source