apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: pipeline-clone-and-build
spec:
  params:
    - name: git-url
    - name: image-name
  workspaces:
    - name: source
  results:
    - name: image-ARTIFACT_INPUTS
      description: Source code used to build the artifact.
      value:
        uri: $(tasks.git-clone.results.url)
        digest: sha1:$(tasks.git-clone.results.commit)
    - name: image-ARTIFACT_OUTPUTS
      description: The artifact that has been built.
      value:
        uri: $(tasks.image-build.results.IMAGE_URL)
        digest: $(tasks.image-build.results.IMAGE_DIGEST)
  tasks:
    - name: git-clone
      taskRef:
        name: git-clone
      params:
        - name: url
          value: $(params.git-url)
      workspaces:
        - name: source
          workspace: source
    - name: image-build
      taskRef:
        name: image-build
      runAfter:
        - git-clone
      params:
        - name: IMAGE
          value: $(params.image-name)
      workspaces:
        - name: source
          workspace: source